# Generated by Django 4.2.24 on 2025-09-29 08:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('transfer_charges', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_sent', models.DecimalField(decimal_places=2, max_digits=18)),
                ('money_received', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_charge', models.DecimalField(decimal_places=4, max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=10, default=Decimal('1'), max_digits=20)),
                ('status', models.CharField(choices=[('F', 'Failure'), ('S', 'Success')], default='S', max_length=2)),
                ('timestamp', models.DateTimeField()),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='api.currency')),
                ('from_useraccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to='api.useraccount')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='api.currency')),
                ('to_useraccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='api.useraccount')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, unique=True)),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='api.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='api.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
