# Generated by Django 4.2.24 on 2025-09-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dummy_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
